name: "Hello World JS Action"
description: "Greet someone and record the time"

inputs:
  pull-request-author:
    description: "The author of the pull request"
    required: true
  pull-request-number:
    description: "The number of the pull request"
    required: true
  repo-owner:
    description: "The owner of the repository"
    required: true
  repo-name:
    description: "The name of the repository"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"